[id]
command = "date +%Y%m%d"
description = "Insert current date in YYYYMMDD format"
insert_type = "Insert"
evaluate = true

[sb]
command = '#CURSOR`#COMMAND`'
description = "Surround with backticks"
insert_type = "Surround"

[sq]
command = '"#COMMAND"'
description = "Surround with quotes"
insert_type = "Surround"

[sl]
command = "IFS=$'\\n' read -rd '' -A #CURSOR <<< $(#COMMAND)"
description = "read in command as a newline delimited list"
insert_type = "Surround"

[ay]
command = " | wl-copy"
description = "Append copy to clipboard"
insert_type = "Append"

[yx]
command = "echo -n '' | wl-copy"
description = "Clear the clipboard"
execute = true

[yy]
command = "wl-copy '#COMMAND'"
description = "Copy the current command to clipboard"
insert_type = "Surround"
execute = true

[y1y]
command = "fc -ln -1 | wl-copy"
description = "Copy the previous command to clipboard"
execute = true

[y2y]
command = "fc -ln -2 | wl-copy"
description = "Copy the previous two commands to clipboard"
execute = true

[y3y]
command = "fc -ln -3 | wl-copy"
description = "Copy the previous three commands to clipboard"
execute = true

[y4y]
command = "fc -ln -4 | wl-copy"
description = "Copy the previous four commands to clipboard"
execute = true

[y5y]
command = "fc -ln -5 | wl-copy"
description = "Copy the previous five commands to clipboard"
execute = true

[y6y]
command = "fc -ln -6 | wl-copy"
description = "Copy the previous six commands to clipboard"
execute = true

[y7y]
command = "fc -ln -7 | wl-copy"
description = "Copy the previous seven commands to clipboard"
execute = true

[y8y]
command = "fc -ln -8 | wl-copy"
description = "Copy the previous eight commands to clipboard"
execute = true

[y9y]
command = "fc -ln -9 | wl-copy"
description = "Copy the previous nine commands to clipboard"
execute = true

[y0y]
command = "fc -ln -10 | wl-copy"
description = "Copy the previous ten commands to clipboard"
execute = true

[gc]
command = 'git commit -m "#CURSOR"'
description = "Start a Git commit"

[gs]
command = "git status"
description = "Git status"
execute = true

[gd]
command = "git diff"
description = "Git diff"
execute = true

[gD]
command = "git diff --staged"
description = "Git diff staged"
execute = true

[gaa]
command = "git add ."
description = "Git add all"
execute = true

[gap]
command = "git add . --patch"
description = "Git add patch -- interactively stage chunks"
execute = true

[gp]
command = "git push #CURSOR"
description = "Start a git push"

[gl]
command = "git pull"
description = "Git pull"
execute = true

[gg]
command = "echo UPDATESTARTUPTTY | gpg-connect-agent"
description = "kick gpg agent"
execute = true

[ps]
command = "sudo "
description = "Prepend sudo"
insert_type = "Prepend"
